version: "3"
services:
  db:
    image: postgres
    container_name: db_filara
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    container_name: redis_social_app
    environment:
      REDIS_REPLICATION_MODE: master
    ports:
     - "6379:6379"

volumes:
  pgdata: